/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rdc_signin_utils_JniMethods */

#ifndef _Included_com_rdc_signin_utils_JniMethods
#define _Included_com_rdc_signin_utils_JniMethods
#ifdef __cplusplus
extern "C" {
#endif
#undef com_rdc_signin_utils_JniMethods_GET_KEY
#define com_rdc_signin_utils_JniMethods_GET_KEY 0L
#undef com_rdc_signin_utils_JniMethods_DEFAULT
#define com_rdc_signin_utils_JniMethods_DEFAULT 1L
/*
 * Class:     com_rdc_signin_utils_JniMethods
 * Method:    getJniKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rdc_signin_utils_JniMethods_getJniKey(JNIEnv *env, jobject thiz){
  return (*env)->NewStringUTF(env,"1234567891234567");
}

#ifdef __cplusplus
}
#endif
#endif
